### ISSUE TITLE
Entry to jackpot is done before confirming the withdraw of balance is successful

### ISSUE THREAD

**Issue by Kirby1997** [TechnoVisionDev/Jackpot#1]
Entry to jackpot is done before confirming the withdraw of balance is successful
https://github.com/TechnoVisionDev/Jackpot/blob/master/src/main/java/com/technovision/jackpot/JackpotManager.java#L47
This means if the withdraw fails for some reason, an entry is still added.

**Comment by TechnoVisionDev** [comment]
Resolved
